esphome:
  name: voip-test-esp32p4

esp32:
  board: esp32-p4-evboard
  variant: ESP32P4
  framework:
    type: esp-idf

# ESP32-C6 Co-Prozessor (falls benötigt für das Dev Kit)
esp32_hosted:
  variant: ESP32C6
  reset_pin: GPIO54
  cmd_pin: GPIO19
  clk_pin: GPIO18
  d0_pin: GPIO14
  d1_pin: GPIO15
  d2_pin: GPIO16
  d3_pin: GPIO17
  active_high: true

external_components:
  - source: components
    components: [voip]

socket:

wifi:
  ssid: "YourWiFiSSID"
  password: "YourWiFiPassword"

# I2S Audio
i2s_audio:
  - id: i2s_out
    i2s_lrclk_pin: GPIO8
    i2s_bclk_pin: GPIO9
  
  - id: i2s_in
    i2s_lrclk_pin: GPIO4
    i2s_bclk_pin: GPIO5

# Mikrofon
microphone:
  - platform: i2s_audio
    id: board_microphone
    adc_type: external
    i2s_audio_id: i2s_in
    i2s_din_pin: GPIO6
    pdm: false
    channel: left
    sample_rate: 16000
    bits_per_sample: 16bit

# Lautsprecher
speaker:
  - platform: i2s_audio
    id: board_speaker
    i2s_audio_id: i2s_out
    dac_type: external
    i2s_dout_pin: GPIO10
    sample_rate: 16000
    bits_per_sample: 16bit

# VoIP-Komponente
voip:
  id: my_voip
  sip_ip: "192.168.1.1"  # Ersetzen Sie durch Ihre SIP-Server-IP
  sip_user: "user"       # Ersetzen Sie durch Ihren SIP-Benutzer
  sip_pass: "password"   # Ersetzen Sie durch Ihr SIP-Passwort
  codec: 0               # 0=PCMU, 1=PCMA, 2=G.721
  mic_gain: 2
  amp_gain: 6
  mic_id: board_microphone
  speaker_id: board_speaker

# Beispiel-Buttons zum Testen
button:
  - platform: template
    name: "Call 123"
    on_press:
      - lambda: id(my_voip).dial("123", "Test Call");

  - platform: template
    name: "Hangup"
    on_press:
      - lambda: id(my_voip).hangup();

# Logger für Debugging
logger:
  level: DEBUG