esphome:
  name: voip-test


esp32:
  board: esp32dev
  framework:
    type: arduino
    version: recommended

external_components:
  - source: components
    components: [voip]

wifi:
  ssid: "YourWiFiSSID"
  password: "YourWiFiPassword"

# VoIP-Komponente
voip:
  id: my_voip
  sip_ip: "192.168.1.1"  # Ersetzen Sie durch Ihre SIP-Server-IP
  sip_user: "user"       # Ersetzen Sie durch Ihren SIP-Benutzer
  sip_pass: "password"   # Ersetzen Sie durch Ihr SIP-Passwort
  codec: 0               # 0=PCMU, 1=PCMA, 2=G.721
  mic_gain: 2
  amp_gain: 6
  # I2S-Konfiguration für Mikrofon (anpassen an Ihre Hardware)
  mic_bck_pin: 26
  mic_ws_pin: 25
  mic_data_pin: 33
  mic_bits: 24
  mic_format: 0
  mic_buf_count: 4
  mic_buf_len: 8
  # I2S-Konfiguration für Verstärker (anpassen an Ihre Hardware)
  amp_bck_pin: 14
  amp_ws_pin: 12
  amp_data_pin: 27
  amp_bits: 16
  amp_format: 0
  amp_buf_count: 16
  amp_buf_len: 60

# Beispiel-Buttons zum Testen
button:
  - platform: template
    name: "Call 123"
    on_press:
      - lambda: id(my_voip).dial("123", "Test Call");

  - platform: template
    name: "Hangup"
    on_press:
      - lambda: id(my_voip).hangup();

# Logger für Debugging
logger:
  level: DEBUG

# Optional: OTA für Updates
ota:
  - platform: esphome  
    password: "ota_password"