esphome:
  name: i2s_test

esp32:
  board: esp32-p4-evboard
  variant: ESP32P4
  build_flags:
    - -UUSE_I2S_LEGACY

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  level: DEBUG
  logs:
    i2s_audio: DEBUG

# I2S Audio: experiment using safe pins
i2s_audio:
  - id: i2s_bus
    # Waveshare ESP32-P4 Dev Kit (ES8311) default pins — shared bus
    i2s_mclk_pin: GPIO13
    i2s_lrclk_pin: GPIO10
    i2s_bclk_pin: GPIO12
    mclk_multiple: 256

microphone:
  - platform: i2s_audio
    id: board_microphone
    adc_type: external
    i2s_audio_id: i2s_bus
    # Waveshare ES8311: DSDIN = GPIO9
    i2s_din_pin: GPIO9
    pdm: false
    channel: left
    sample_rate: 8000
    bits_per_sample: 16bit
    # Log when audio chunks are received. The lambda receives `x` (vector<uint8_t>) as arg.
    on_data:
      - then:
          - lambda: |-
              ESP_LOGD("i2s_test", "Received microphone data bytes=%d", x.size());

switch:
  - platform: template
    name: "Start Mic"
    optimistic: true
    turn_on_action:
      - lambda: |-
          id(board_microphone).start();
    turn_off_action:
      - lambda: |-
          id(board_microphone).stop();
