esphome:
  name: p4sip
  friendly_name: p4sip
 #platformio_options:
 #   board_build.flash_mode: dio


logger:
  level: DEBUG
  baud_rate: 115200
  hardware_uart: USB_SERIAL_JTAG
#  level: VERBOSE
#  logs:
#    voice_assistant: VERBOSE
#    api: DEBUG
#    i2s_audio: DEBUG


esp32:
  board: esp32-p4-evboard # Waveshare ESP32-P4 Dev Kit
  variant: ESP32P4
  flash_size: 16MB
  framework:
    type: esp-idf

# ESP32-C6 Co-Prozessor (falls benötigt für das Dev Kit)
esp32_hosted:
  active_high: true
  variant: ESP32C6
  reset_pin: GPIO54
  cmd_pin: GPIO19
  clk_pin: GPIO18
  d0_pin: GPIO14
  d1_pin: GPIO15
  d2_pin: GPIO16
  d3_pin: GPIO17
#update:
#  - platform: esp32_hosted
#    #path: C:\dev\GitHub\EspHomeVoipLib\ESP-Hosted-NG-release_v1.0.4.0.0\esp32c6\sdio+uart\network_adapter.bin
#    #sha256: 4f9d418a11f88966f99b92a7ecfd9a6bdbd10f84f1d3c7f7603ca0a87a323757
#    #path: C:\dev\GitHub\EspHomeVoipLib\ESP-Hosted-NG-release_v1.0.4.0.0\esp32c6\sdio_only\network_adapter.bin
#    #sha256: 8423777db42f19fac8a80694b66abf292ad768f11a9257478c8b667910508071
#    path: C:\dev\GitHub\EspHomeVoipLib\ESP-Hosted-NG-release_v1.0.4.0.0\esp32c6\spi_only\network_adapter.bin
#    sha256: f84eda790f7977c88fef7b0bf8cea87a54dedf9e271892c84726cd7dfd785b65    
#    name: "C6 Coprocessor Update"


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:


api:
#  encryption:
#    key: !secret api_encryption_key   


ota:
  - platform: esphome
#    password: !secret ota_password


web_server:
  

captive_portal:


external_components:
  - source: components
  #- source: github://andreaswatch/EspHomeVoipLib
    refresh: 1s
    components: [voip, mic_recorder]


# I2S Audio
i2s_audio:
  - id: i2s_bus
    # Waveshare ESP32-P4 Dev Kit (ES8311) default pins — shared I2S bus
    i2s_mclk_pin: GPIO13
    i2s_lrclk_pin: GPIO10
    i2s_bclk_pin: GPIO12


# Mikrofon
microphone:
  - platform: i2s_audio
    id: board_microphone
    adc_type: external
    i2s_audio_id: i2s_bus
    # Waveshare ES8311: DSDIN = GPIO9
    i2s_din_pin: GPIO9
    pdm: false
    channel: left
    sample_rate: 8000
    bits_per_sample: 16bit

# Lautsprecher
speaker:
  - platform: i2s_audio
    id: board_speaker
    i2s_audio_id: i2s_bus
    dac_type: external
    # Waveshare ES8311: ASDOUT = GPIO11
    i2s_dout_pin: GPIO11
    sample_rate: 8000
    bits_per_sample: 16bit

## VoIP-Komponente
#voip:
#  id: my_voip
#  sip_ip: "192.168.178.1"  # Ersetzen Sie durch Ihre SIP-Server-IP
#   sip_user: !secret sip_user       # Ersetzen Sie durch Ihren SIP-Benutzer
#   sip_pass: !secret sip_password   # Ersetzen Sie durch Ihr SIP-Passwort
#   codec: 0               # 0=PCMU, 1=PCMA, 2=G.721
#   mic_gain: 2
#   amp_gain: 6
#   mic_id: board_microphone
#   speaker_id: board_speaker
#   # Optional events to control PA (amplifier) via automations
#   on_call_established:
#     - then:
#       - switch.turn_on: pa_power
#   on_call_ended:
#     - then:
#       - switch.turn_off: pa_power
#   on_ready:
#     - then:
#       - logger.log: "VoIP: hardware ready"
#   on_not_ready:
#     - then:
#       - logger.log: "VoIP: hardware not ready"
#   # Optional: Use on_ready/on_not_ready automations for readiness; start_on_boot can auto-start component
#   # If you want the VoIP component to auto start on boot when hardware is ready, enable:
#   start_on_boot: false
# 
# # Microphone recorder component for download/record
mic_recorder:
  id: mic_recorder1
  mic_id: board_microphone


button:
  - platform: template
    name: "Mic Download 1s"
    on_press:
      - lambda: |-
          if (id(mic_recorder1) != nullptr) id(mic_recorder1).record_for_ms(1000);


# 
# 
# # Beispiel-Buttons zum Testen
# button:
#   - platform: template
#     name: "Call 017623575599"
#     on_press:
#       - lambda: id(my_voip).dial("017623575599", "Test Call");
# 
#   - platform: template
#     name: "Hangup"
#     on_press:
#       - lambda: id(my_voip).hangup();
# 
#   - platform: template
#     name: "Record 1s & play back"
#     on_press:
#       - lambda: |-
#           id(my_voip).record_and_playback_1s();
# 
#  # - platform: template
#  #   name: "Mic Download 1s"
#  #   on_press:
#  #     - lambda: |-
#  #         if (id(mic_recorder1) != nullptr) id(mic_recorder1).record_for_ms(1000);
# 
#   - platform: template
#     name: "Beep 200ms"
#     on_press:
#       - switch.turn_on: pa_power
#       - delay: 50ms
#       - lambda: |-
#           if (id(my_voip) != nullptr) id(my_voip).play_beep_ms(200, 4.0);
#       - delay: 700ms
#       - switch.turn_off: pa_power
# 
#   - platform: template
#     name: "Beep 1s"
#     on_press:
#       - switch.turn_on: pa_power
#       - delay: 100ms
#       - lambda: |-
#           if (id(my_voip) != nullptr) id(my_voip).play_beep_ms(1000, 2.0);
#       - delay: 1200ms
#       - switch.turn_off: pa_power
# 
# 
# switch:
#   - platform: template
#     name: "Start VoIP"
#     id: start_voip_switch
#     optimistic: true
#     restore_mode: RESTORE_DEFAULT_OFF
#     turn_on_action:
#       - lambda: |-
#           if (id(my_voip) != nullptr) {
#             id(my_voip).start_component();
#           }
#     turn_off_action:
#       - lambda: |-
#           if (id(my_voip) != nullptr) {
#             id(my_voip).hangup();
#             id(my_voip).stop_component();
#           }
# 
#   - platform: output
#     name: "PA Power"
#     id: pa_power
#     output: pa_ctrl
#     restore_mode: ALWAYS_ON
# 
# 
# 
# # Optional pin to control amplifier on the Waveshare board (PA_Ctrl)
# output:
#   - platform: gpio
#     pin: GPIO53
#     id: pa_ctrl
#     inverted: false
#     #restore_mode: ALWAYS_OFF
#     #restore_mode: RESTORE_DEFAULT_OFF
# 